server:
  port: 7100
spring:
  application:
    name: springcloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/myNameIssls/springcloud-study/tree/master/springcloud-zuul
